#!/bin/bash
# Copyright 2014 overflowerror (https://github.com/overflowerror/)
#
# This file is part of Anineko.
#
# Anineko is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Anineko is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Anineko.  If not, see <http://www.gnu.org/licenses/>.

echo "Welcome to the Anineko install/update-script."

if test $(id -u) != 0; then
	echo "Error: Not permitted. You need to be root in order to execute this script."
	exit 2
fi

check() {
	text="  $1..."
	echo -n $text
	for i in $(seq ${#text} 20); do
		echo -n " "
	done
	which $1 2>&1 > /dev/null
	if test $? = 0; then
		echo -e "[ \033[32mpass\033[0m ]"
		return 0
	else
		echo -e "[ \033[31mfail\033[0m ]"
		echo "Please resolve dependency problemes and retry."
		exit 3
	fi
}

echo
echo "Checking dependencies..."
check wget
check grep
check egrep
check sed
check awk
check md5sum
check python
check tee
check bc

echo
echo "The latest version of Anineko will now be downloaded to /usr/bin/."
echo "Press [enter] to continue. Press [ctrl] + C to abort."
read

wget -O /usr/bin/anineko "https://raw.githubusercontent.com/overflowerror/Anineko/master/anineko" --progress=bar:force 2>&1 | tail -f -n +12

chmod o+x /usr/bin/anineko

echo
echo "Download complete. Have fun with Anineko. :3"

exit 0
